name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # 프로젝트에 맞는 Node.js 버전 사용

      - name: Install dependencies
        working-directory: ./netflix
        run: npm install

      - name: Create .env.production
        working-directory: ./netflix
        run: |
          echo "REACT_APP_IP_ADDRESS=https://daeuning.github.io/WSD-Assignment-02" > .env.production
          echo "REACT_APP_PORT=443" >> .env.production
          echo "REACT_APP_TMDB_API_KEY=${{ secrets.REACT_APP_TMDB_API_KEY }}" >> .env.production
          echo "REACT_APP_KAKAO_REST_API_KEY=${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}" >> .env.production
          echo "REACT_APP_KAKAO_REDIRECT_URI=https://daeuning.github.io/WSD-Assignment-02/kakao-login-success" >> .env.production

      - name: Fix permissions for react-scripts
        working-directory: ./netflix
        run: chmod +x ./node_modules/.bin/react-scripts

      - name: Build project
        working-directory: ./netflix
        run: npm run build:prod # 빌드 명령어 (React, Vue, Angular 등 프로젝트에 따라 변경)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./netflix/build # 빌드 출력 디렉토리 (React: build, Vue: dist)
